version: '3.3'
services:
  job:
    image: job-demo:latest
    container_name: 'job-demo'
    build:
      context: ./
      dockerfile: Dockerfile
  prometheus:
    image: prom/prometheus:v2.7.2
    container_name: 'prometheus'
    ports:
      - '9090:9090'
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  pushgateway:
    image: prom/pushgateway:v0.6.0
    container_name: 'pushgateway'
    ports:
      - '9091:9091'

  grafana:
    image: grafana/grafana:6.0.2
    container_name: 'grafana'
    ports:
      - '3000:3000'
    volumes:
      - ./monitoring/grafana/:/etc/grafana/      
    env_file:
      - ./monitoring/grafana/config.monitoring
    environment:
      - GF_INSTALL_PLUGINS=snuids-trafficlights-panel
    depends_on:
      - prometheus   